### ISSUE TITLE
Update PIP subpackages for MuJoCo 2.1.1

### ISSUE THREAD

**Issue by kevinzakka** [deepmind/dm_robotics#5]
Hi!

Big fan of the subpackages in this repo such as `dm_robotics-transformations`. Would it be possible to upload binaries that support the latest MuJoCo version? I can't use them at the moment because they require MuJoCo 210.

Cheers!

**Comment by shacklestone** [comment]
This is an oversight on my part.

Since it's a minor release, and I don't believe any of the API we use has changed between 2.1.0 and 2.1.1 I think you should be able to create a 2.1.0 symlink that points to the 2.1.1 version of the mujoco `.so` file.

However, that's not ideal.  We will cut a new release that expects to load MuJoCo 2.1.1

**Comment by kevinzakka** [comment]
Thanks @shacklestone!

**Comment by shacklestone** [comment]
The newly released version 0.3.0 of these packages depend on `dm_control == 0.0.425341097` which expects MuJoCo 2.1.1.

**Comment by shacklestone** [comment]
Also note, that `transformations` will attempt to import NumPy Quaternion and use that library to speed up some operations, if it is present (https://github.com/moble/quaternion)

**Comment by kevinzakka** [comment]
Worked like a charm, thank you so much @shacklestone !
