### ISSUE TITLE
Direct Velocity or Position Control

### ISSUE THREAD

**Issue by ava6969** [deepmind/dm_robotics#8]
iS IT POSSIBLE TO BYPASS THE CARTESIAN CONTROLLER AND CONTROL IN JOINT SPACE DIRECTLY.

**Comment by shacklestone** [comment]
Yes.

Environments typically start with joint control, Cartesian control is added on top of that.

For example, in [RGB stacking](https://github.com/deepmind/rgb_stacking), we start with a [joint velocity controller](https://github.com/deepmind/rgb_stacking/blob/main/rgb_stacking/task.py#L240), then a [6-DoF cartesian controller](https://github.com/deepmind/rgb_stacking/blob/main/rgb_stacking/task.py#L275) is made that delegates to the joint controller, finally, a 4-DoF cartesian controller is created that delegates to the 6-DoF cartesian controller.

The 4-DoF controller is the exposed to the agent by setting it as the `arm_effector` [in the StandardRobot initializer](https://github.com/deepmind/rgb_stacking/blob/main/rgb_stacking/task.py#L321).

If you want to change your action space, change this effector.  You could use a joint velocity controller or [create your own effector](https://github.com/deepmind/dm_robotics/blob/main/py/moma/effector.py) (E.g. a PD based position controller) the api is mainly `action_spec` (input names and ranges) and `set_control` which decides how actions are interpreted,

**Comment by shacklestone** [comment]
Also note, you can use create your own [`ActionSpace`](https://github.com/deepmind/dm_robotics/blob/main/py/agentflow/core.py#L112) if you want to change actions without using an effector.  But since the choice between cartesian vs joint space control is made by effector choice (for RGB stacking) that would be the place to start for that task.

`ActionSpace`s are widely employed for things like [casting actions to be of the same type](https://github.com/deepmind/dm_robotics/blob/main/py/agentflow/action_spaces.py#L140), [clipping or limiting action values](https://github.com/deepmind/dm_robotics/blob/main/py/agentflow/action_spaces.py#L379), [changing the control frame](https://github.com/deepmind/dm_robotics/blob/main/py/moma/action_spaces.py#L111) and others

**Comment by ava6969** [comment]
> wow, beautiful interface, what do you advice with respect to reducing the substeps. if i use the direct velocity control. i don't expect to have to need 100 substeps, as must suite i used in the past works well even for 4 substeps.

@shacklestone

**Comment by josechenf** [comment]
Sorry, could you elaborate what you mean by substeps? Do you mean the control rate?

**Comment by ava6969** [comment]
yes so adjusting the control timeteps and physics timesteps. if i adjust it to reduce the substeos. so to make CONTROL_TIMESTEPS/PHYSICS_TIMESTEP smaller.

**Comment by josechenf** [comment]
Here is what you can achieve:

- By changing the control timestep you will change at which frequency the agent is able to send a command. You can easily play around with this.
- By changing the physics timestep you will make the simulation go faster overall and have less physics timestep. However, this is not advised as it might render the simulation less stable

**Comment by ava6969** [comment]
Thank you
